language: c
compiler: arm-none-eabi-gcc

before_install:
    - sudo apt-get install --install-recommends gcc-arm-none-eabi
    

script: 
    - cmake . && make
    # - make VERBOSE=1 --no-print-directory


notifications: 
    email: false